from flask_jwt_extended import decode_token

token = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJmcmVzaCI6ZmFsc2UsImlhdCI6MTc0MDk0MTYyMSwianRpIjoiZDQ0Zjc4NWMtNzgwNy00YzJkLWEzNmYtYjQ1NmQxMTY1Nzk0IiwidHlwZSI6ImFjY2VzcyIsInN1YiI6eyJpZCI6NSwicm9sZSI6InN0dWRlbnQifSwibmJmIjoxNzQwOTQxNjIxLCJjc3JmIjoiMDZmMmQxMGQtYWQ4Mi00ZTFiLTgyNTktYTMxZjdlNThhOWNhIiwiZXhwIjoxNzQxMDI4MDIxfQ.BhkFEr67UkxrdMGsGjqnRgKDlYEYnpUlayZ78X9NxUo"

decoded = decode_token(token)
print(decoded)
